---
title: "Quirkle Scores"
author: "Nathan Hoteling"
output: 
  html_document:
    css: "css/styles.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(lubridate)
library(dplyr)
library(tidyr)
library(htmltools)
library(readr)
library(stringr)
library(plotly)

library(r2d3)

```

```{r, echo=FALSE}
# Add image by title
htmltools::img(src = knitr::image_uri(file.path(getwd(),"img/quirkle-greens.png")),
               style = 'position:absolute; top:10px; left:415px; padding:10px; width:300px; opacity:0.7')

# https://stackoverflow.com/questions/43009788/insert-a-logo-in-upper-right-corner-of-r-markdown-html-document/43010632
# https://bookdown.org/yihui/rmarkdown-cookbook/latex-logo.html
```


Scores from family Quirkle matches, last updated <b> `r format(Sys.time(), '%B %d, %Y')` </b>.

```{r, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
# Function to remove "T" from date string
# "T" is appended to the date string so Excel doesn't
# mess it up when the file is opened
rmT <- function(fstr) { stringr::str_replace(fstr, "T", "") }

# Read data file
df.raw <- read.csv("data/quirklescores.csv", header=TRUE) %>%
  mutate(date = ymd(rmT(date)))

# Cumulative scores
matches <- unique(df.raw$match)
d <- lapply(seq_along(matches), function(i) {
  df <- df.raw %>% filter(match == matches[i])
  df$CLu <- cumsum(df$Lu)
  df$CCr <- cumsum(df$Cr)
  df$CCo <- cumsum(df$Co)
  df$CNa <- cumsum(df$Na)
  return(df)
})
df.scores <- do.call(rbind,d)

# Rearrange for plotting
df.quirkle <- df.scores %>% 
  select(match, round, Lu, Cr, Co, Na) %>%
  pivot_longer(cols = c("Lu", "Cr", "Co", "Na")) %>%
  mutate(name = factor(name, levels = c("Co","Lu","Cr","Na"))) %>%
  arrange(match, round, name)
```


```{r, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
# Useful parameters
df.totals <- df.quirkle %>% group_by(match, name) %>% summarise(score = sum(value, na.rm=TRUE))
max_round <- max(df.quirkle$round)
max_value <- max(df.quirkle$value, na.rm=TRUE)
max_score <- max(df.totals$score)

# First try at the figure, with circles... 
# this one didn't make the cut
p1 <- ggplot(df.quirkle, aes(group=match)) +
  geom_point(aes(x=round, y=name, size=value, color=name, alpha=value)) +
  scale_size_area(max_size=8) +
  facet_wrap(~match, ncol=1) +
  labs(x="Round", y = "") +
  geom_rect(data=df.totals, 
            aes(xmin = max_round+1, xmax = max_round+1+3*score/max_score,
                ymin = as.integer(name), ymax = as.integer(name)+1,
                fill=name, color=name), alpha=0.6, size=0) +
  theme_minimal() +
  theme(strip.background = element_blank(),
  strip.text.x = element_blank(),
  legend.position = "none",
  axis.text.y = element_blank())

# Summary figure
p2 <- ggplot(df.quirkle, aes(group=match)) +
  geom_linerange(aes(xmin=-Inf, xmax=max_round+1, y=as.integer(name)+0.5), 
                 size=0.2, color="grey90", alpha=0.4) +
  geom_rect(aes(xmin=round-0.5*value/max_value, xmax=round+0.5*value/max_value, 
                ymin=as.integer(name), ymax=as.integer(name)+1, 
                fill=name, color=name, alpha=value),
            size=0) +
  geom_rect(data=df.totals, 
            aes(xmin = max_round+1, xmax = max_round+1+2*score/max_score,
                ymin = as.integer(name), ymax = as.integer(name)+1,
                fill=name, color=name), alpha=0.6, size=0) +
  geom_text(data=df.totals, 
            aes(x = max_round+1+2*score/max_score,
                y = as.integer(name), label=score), 
            color="grey65", size=3, hjust=-0.2, vjust=-0.5) +
  scale_size_area(max_size=8) +
  scale_x_continuous(breaks = c(0,5,10,15)) +
  labs(x = "Round", y = "") +
  facet_wrap(~desc(match), ncol=1) +
  theme_void() +
  #theme_minimal() +
  theme(strip.background = element_blank(),
  strip.text.x = element_blank(),
  legend.position = "none",
  axis.text.y = element_blank(),
  axis.text.x = element_text(size=10, color="grey65"),
  axis.title.x = element_text(size=12, color="grey55"))
  
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=6, fig.height=8}
# Draw the figure in the document
p2
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=6, fig.height=8}
# Create ggplotly figure from the ggplot
#
# ggplotly does a lot of things automatically that are
# diffucult to change:
# - I can't seem to disable tooltips, only change the text
# - ggplotly adds axis lines even though I removed them for ggplot
# - sizes & text positions need a little adjustment in some cases
#

fig <- ggplotly(p2) %>% 
  style(textposition = "top right")

# Change hover text for data points
new_text <- function(fig, i) {
  v <- fig$x$data
  x0 <- v[[i]]$name
  x1 <- parse_number(str_sub(v[[i]]$text, str_locate(v[[i]]$text, "match:")[2]))
  x2 <- mean(v[[i]]$x[1:4])
  x3 <- round(max_value * (v[[i]]$x[4] - v[[i]]$x[1]))  # max_value from chunk above
  text <- paste("name: ",x0, "<br />",
                "match: ", x1, "<br />",
                "round: ", x2, "<br />",
                "points: ", x3, 
                sep = "")
  return(text)
}

len <- length(fig$x$data)
nmatches <- length(unique(df.quirkle$match))

# change the tooltips
for (i in (nmatches+1):344) {
  fig$x$data[[i]]$text <- new_text(fig, i)
}

# change tooltips for bars
for (i in 345:len-nmatches) {
  fig$x$data[[i]]$text <- "" 
}

# change toolstips for text
for (i in (len-nmatches+1):len) {
  fig$x$data[[i]]$hovertext <- "" 
}

# Draw the ggplotly figure
fig
```



```{r, include=FALSE, echo=FALSE, warning=FALSE, message=FALSE}
#
# Prepare data for d3 vis
d.data <- list(quirkle = df.quirkle[ complete.cases(df.quirkle), ], totals = df.totals)
dd <- jsonlite::toJSON(d.data)

# Write json file for my pure d3.js version
write(dd,"data/quirkle.json")

```

```{d3, data=dd, height=900, width=800,dependencies=list("js/d3-tip.js", "js/d3-legend.js"), css="css/styles.css"}
 // D3 code chunk


// Scales //
var colorScale = d3.scaleOrdinal().domain(["Na", "Cr", "Lu", "Co"])
                   .range(['#ddaeff','#67d9dc','#b0cf66','#fbada7']);
                   
var nameScale = d3.scaleBand()
                  .domain(["Na", "Cr", "Lu", "Co"])
                  .range([0, 60, 100, 140]);
var yScale = d3.scaleLinear()
               .domain([9, 20])
               .range([800,1]);
var xScale = d3.scaleLinear()
               .domain([1,18])
               .range([10,450]);
var alphaScale = d3.scaleSqrt()
                   .domain([1,24])
                   .range([0.3,1.0]);
var barScale = d3.scaleLinear()
                 .domain([70,150])
                 .range([25,75]);




/////////////////////////////////////////////////////////////
// Create SVG element
// (Not used for r2d3, but needed for js stuff)
//var svg = d3.select("body")
//			.append("svg")
//			.attr("width", width)
//			.attr("height", height);
////////

// Tooltips
var tip = d3.tip()
  .attr('class', 'd3-tip')
  //.attr('pointer-events','none')
  .offset([-5, 0])
  .html(function(d) { return d.value; });
svg.call(tip);

svg.selectAll("line")
  .data(data.totals)
  .enter()
    .append("line")
      .attr("x1", function(d, i) { return xScale(1); })
      .attr("y1", function(d, i) { return yScale(d.match) + nameScale(d.name) + 7.5; })
      .attr("x2", function(d, i) { return xScale(19); })
      .attr("y2", function(d, i) { return yScale(d.match) + nameScale(d.name) + 7.5; })
      .style("stroke", "#dcdcdc")     // "#dcdcdc"
      .style("stroke-width", "1px")
      .style("pointer-events","none");
      
// Bars at right of figure
svg.selectAll('rect')
  .data(data.totals)
  .enter()
  //.append("g")
  //.attr("class","bars")
    .append('rect')
      .attr('width', function(d, i) { return barScale(d.score); })
      .attr('height', '15px')
      .attr('x', function(d, i) { return xScale(19); })
      .attr('y', function(d, i) { return yScale(d.match) + nameScale(d.name); })
      .attr('fill', function(d, i) { return colorScale(d.name); })
      .attr('opacity', 0.8);

// Bar labels
svg.selectAll('text')
   .data(data.totals)
   .enter()
   .append('text')
      .text(function(d, i) { return d.score; })
      .attr('x', function(d, i) { return xScale(19) + barScale(d.score) + 5;})
      .attr('y', function(d, i) { return yScale(d.match) + nameScale(d.name) + 12; })
      .attr('font-size', '11px')
      .attr('fill', 'grey');

// Data points
svg.selectAll('g')
  .data(data.quirkle)
  .enter()
  .append("g")
  .attr("class","boxes")
    .append('rect')
      .attr('width', function(d, i) { return d.value; })
      .attr('height', '15px')
      .attr('x', function(d, i) { return xScale(d.round) - 0.5*d.value;})
      .attr('y', function(d, i) { return yScale(d.match) + nameScale(d.name); })
      .attr('fill', function(d, i) { return colorScale(d.name); })
      .attr('opacity', function(d, i) { return alphaScale(d.value); })
      .on("mouseover",tip.show)
			.on("mouseout",tip.hide);


```

